version: '3.8'
services:
  formflow-app:
    build: .
    ports:
      - "${APP_HOST_PORT:-8080}:5000"
    env_file:
      - .env
    volumes:
      - ./pdf_output:/app/pdfs:Z
      - ./forms:/app/forms:Z
      - ./pdf_templates:/app/pdf_templates:Z
      - ./static:/app/static:Z
      - ./drafts:/app/drafts:Z
    restart: unless-stopped
