services:
  formflow-app:
    build: .
    ports:
      - "${APP_HOST_PORT:-8080}:5000"
    env_file:
      - .env
    volumes:
      - ./pdf_output:/app/pdfs:Z
      - ./forms:/app/forms:Z
      - ./pdf_templates:/app/pdf_templates:Z
      - ./static:/app/static:Z
    restart: unless-stopped
    depends_on:
      - smb-server

  smb-server:
    image: dperson/samba
    # ports:
    #   - "139:139"
    #   - "445:445"
    environment:
      - USERID=0
      - GROUPID=0
      - USER=testuser;testpass
      - SHARE=pdfs;/share;yes;no;yes;testuser
    volumes:
      - ./smb_data:/share:Z
    restart: unless-stopped
